name: johnhogan
favicon: null
layout_spectrum: 0.744739088229835
typography_spectrum: 0.7901986455544829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3796693463809788
  lightness: 0.9154276042245328
  saturation: 0.5852362853474915
  rhythmicContrast: 0.26527606323361397
purpose: []
