color:
  brandStrength: 0.375
  saturation: 0.5852362853474915
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.9154276042245328
  rhythmicContrast: 0.265276063233614
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.744739088229835
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: johnhogan
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7901986455544829
