name: john hogan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58966
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: John Hogan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74306449-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
